package pojos;
// Generated Mar 4, 2016 8:35:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicine generated by hbm2java
 */
public class Medicine  implements java.io.Serializable {


     private MedicineId id;
     private User user;
     private String medicienName;
     private boolean notification;
     private String medicienDate;
     private String medicienTime;
     private String medicienInterval;
     private String medicienAppearance;
     private Integer medicienDose;

    public Medicine() {
    }

	
    public Medicine(MedicineId id, User user, String medicienName, boolean notification, String medicienDate) {
        this.id = id;
        this.user = user;
        this.medicienName = medicienName;
        this.notification = notification;
        this.medicienDate = medicienDate;
    }
    public Medicine(MedicineId id, User user, String medicienName, boolean notification, String medicienDate, String medicienTime, String medicienInterval, String medicienAppearance, Integer medicienDose) {
       this.id = id;
       this.user = user;
       this.medicienName = medicienName;
       this.notification = notification;
       this.medicienDate = medicienDate;
       this.medicienTime = medicienTime;
       this.medicienInterval = medicienInterval;
       this.medicienAppearance = medicienAppearance;
       this.medicienDose = medicienDose;
    }
   
    public MedicineId getId() {
        return this.id;
    }
    
    public void setId(MedicineId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMedicienName() {
        return this.medicienName;
    }
    
    public void setMedicienName(String medicienName) {
        this.medicienName = medicienName;
    }
    public boolean isNotification() {
        return this.notification;
    }
    
    public void setNotification(boolean notification) {
        this.notification = notification;
    }
    public String getMedicienDate() {
        return this.medicienDate;
    }
    
    public void setMedicienDate(String medicienDate) {
        this.medicienDate = medicienDate;
    }
    public String getMedicienTime() {
        return this.medicienTime;
    }
    
    public void setMedicienTime(String medicienTime) {
        this.medicienTime = medicienTime;
    }
    public String getMedicienInterval() {
        return this.medicienInterval;
    }
    
    public void setMedicienInterval(String medicienInterval) {
        this.medicienInterval = medicienInterval;
    }
    public String getMedicienAppearance() {
        return this.medicienAppearance;
    }
    
    public void setMedicienAppearance(String medicienAppearance) {
        this.medicienAppearance = medicienAppearance;
    }
    public Integer getMedicienDose() {
        return this.medicienDose;
    }
    
    public void setMedicienDose(Integer medicienDose) {
        this.medicienDose = medicienDose;
    }




}


