package pojos;
// Generated Mar 4, 2016 8:35:07 AM by Hibernate Tools 4.3.1



/**
 * MedicineId generated by hbm2java
 */
public class MedicineId  implements java.io.Serializable {


     private int medicienId;
     private int userId;

    public MedicineId() {
    }

    public MedicineId(int medicienId, int userId) {
       this.medicienId = medicienId;
       this.userId = userId;
    }
   
    public int getMedicienId() {
        return this.medicienId;
    }
    
    public void setMedicienId(int medicienId) {
        this.medicienId = medicienId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MedicineId) ) return false;
		 MedicineId castOther = ( MedicineId ) other; 
         
		 return (this.getMedicienId()==castOther.getMedicienId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMedicienId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


